# Generated by Django 2.1.7 on 2019-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0012_auto_20190417_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
