# Generated by Django 2.1.7 on 2019-04-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0013_devicedata_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='time',
            new_name='request_time',
        ),
    ]
