# Generated by Django 2.1.7 on 2019-05-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0019_auto_20190502_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={'verbose_name': 'Device data', 'verbose_name_plural': 'Device data'},
        ),
        migrations.AlterModelOptions(
            name='devicesettings',
            options={'verbose_name': 'Device location', 'verbose_name_plural': 'Device location'},
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='order',
        ),
        migrations.RemoveField(
            model_name='devicesettings',
            name='order',
        ),
    ]
