# Generated by Django 2.1.7 on 2019-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0020_auto_20190502_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_limit', models.IntegerField(default=0)),
                ('down_limit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Device limit',
                'verbose_name_plural': 'Device limits',
            },
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='down_limit',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='up_limit',
        ),
    ]
