# Generated by Django 2.1.7 on 2019-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0022_auto_20190518_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelimit',
            name='down_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicelimit',
            name='up_limit',
            field=models.IntegerField(default=0),
        ),
    ]
