# Generated by Django 2.2.1 on 2019-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0024_logdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='imei_code',
            field=models.CharField(max_length=255, verbose_name='Cihaz ID'),
        ),
    ]
