# Generated by Django 2.2.1 on 2019-05-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0027_auto_20190520_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='battery',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatur'),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='bin_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatur'),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='imei_code',
            field=models.CharField(max_length=255, verbose_name='Cihaz ID'),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='request_time',
            field=models.CharField(max_length=255, verbose_name='Sorğu zamanı'),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='imei_code',
            field=models.CharField(max_length=255, verbose_name='Cihaz ID'),
        ),
    ]
