# Generated by Django 2.2.1 on 2019-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasco_app', '0028_auto_20190520_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdata',
            old_name='temperature',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='humidity',
            new_name='bin_state',
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='bin_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rütubət'),
        ),
    ]
